image: node:alpine

pages:
  cache:
    paths:
      - node_modules/

  stage: deploy
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --configuration=production --base-href https://der-eine-aegyptische-gott.gitlab.io/cms-ui/
  artifacts:
    paths:
      - public
  only:
    - master
