image: node:alpine

pages:
  cache:
    paths:
      - node_modules/

  stage: deploy
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --configuration=production
  artifacts:
    paths:
      - public
  only:
    - master
